version: "3.9"

services:

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shriramya
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:latest
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - mysql
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: shriramya
      WORDPRESS_CONFIG_EXTRA: |
        @ini_set( 'upload_max_filesize', '64M' );
        @ini_set( 'post_max_size', '64M' );
        @ini_set( 'memory_limit', '256M' );

  mongodb:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: always
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - mysql
    environment:
      MONGO_URL: mongodb://mongodb:27017/
      DB_NAME: shriramya
      WOOCOMMERCE_URL: http://wordpress:80
      WOOCOMMERCE_CONSUMER_KEY: ck_1d948ab5af225784a4c0545e0e8fbc735b7440d1
      WOOCOMMERCE_CONSUMER_SECRET: cs_903da4d006d7939f2e59caecc8068e178d61afc9
      WOOCOMMERCE_VERIFY_SSL: "False"
    volumes:
      - upload_data:/app/uploads

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    env_file:
      - backend/.env

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
      - wordpress

volumes:
  mysql_data:
  wordpress_data:
  mongo_data:
  upload_data:
